<?php
namespace PhoneNumber;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-09-11 at 15:08:18.
 */
class UtilsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Utils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Utils;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PhoneNumber\Utils::safeParsePhoneNumbers
     * @todo   Implement testSafeParsePhoneNumbers().
     */
    public function testSafeParsePhoneNumbers()
    {
        $phoneNumbers= Utils::safeParsePhoneNumbers(" + 7 (912 ) 906 48-6 3 , 8 (34 -62) 55- 15 5 -5");
        $this->assertSame(sizeof($phoneNumbers), 2);
        $this->assertSame("551555", $phoneNumbers[1]->getLocal());
    }

    /**
     * @covers PhoneNumber\Utils::getFirstMobileNumber
     * @todo   Implement testGetFirstMobileNumber().
     */
    public function testGetFirstMobileNumber()
    {
        $this->assertSame("9064863", Utils::getFirstMobileNumber(Utils::safeParsePhoneNumbers(" 8 (34 -62) 55- 15 5 -5, + 7 (912 ) 906 48-6 3 ,"))->getLocal());
    }
}
